server:
    port: 7090
    servlet:
        context-path: /api
        session:
            timeout: PT60M

spring:
    web:
        resources:
            add-mappings: false
    servlet:
        multipart:
            max-file-size: 15MB
            max-request-size: 15MB

    datasource:
        url: jdbc:mysql://39.102.209.30:3306/easypan?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
        username: root
        password: zzk814abc
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            pool-name: HikariCPDatasource
            minimum-idle: 5
            idle-timeout: 180000
            maximum-pool-size: 10
            auto-commit: true
            max-lifetime: 1800000
            connection-timeout: 30000
            connection-test-query: SELECT 1

    mail:
        host: smtp.qq.com
        port: 465
        username: 2899725367@qq.com
        password: wuurysewlaehdcei  #授权码
        protocol: smtp
        properties:
            mail:
                smtp:
                    auth: true
                    starttls.enable: true
                    ssl.enable: true

    data:
        redis:
            database: 0
            host: 39.102.209.30
            port: 6379
            timeout: 2000

logging:
    level:
        root: info

admin:
    emails: kunyyds888@outlook.com

dev: false

# TODO: QQ扫码登录

#OSS




